# Generated by Django 3.2 on 2023-01-04 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiListId',
            fields=[
                ('atcId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fdPrdtNm', models.CharField(default='', max_length=500, null=True)),
                ('fdFilePathImg', models.CharField(max_length=300)),
                ('fdSbjt', models.CharField(max_length=500)),
                ('depPlace', models.CharField(max_length=30)),
                ('fdYmd', models.DateField(max_length=10, null=True)),
                ('category', models.CharField(max_length=20)),
                ('clrNm', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('upper_category', models.CharField(max_length=20)),
                ('middle_category', models.CharField(max_length=20)),
                ('lower_category', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DollidoLstId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lstPrdtNm', models.CharField(blank=True, max_length=200, null=True, verbose_name='습득물 이름')),
                ('lstFilePathImg', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='사진 등록')),
                ('lstcontent', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='특이사항')),
                ('lstYmd', models.CharField(blank=True, max_length=200, null=True, verbose_name='습득일자')),
                ('lstPlace', models.CharField(blank=True, max_length=200, null=True)),
                ('create_date', models.DateTimeField(default='2023-01-04 10:18:52')),
                ('find_status', models.BooleanField(default=False)),
                ('clrNm', models.CharField(blank=True, max_length=10, null=True)),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name_plural': '돌리도 게시판',
            },
        ),
    ]
