# Generated by Django 3.2 on 2022-12-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dollidolstid',
            name='create_date',
            field=models.DateTimeField(default='2022-12-27 15:39:01'),
        ),
        migrations.AlterField(
            model_name='dollidolstid',
            name='lstPlace',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dollidolstid',
            name='lstYmd',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
