# Generated by Django 3.2 on 2022-12-21 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dollidolstid',
            name='user',
        ),
    ]
