# Generated by Django 3.2 on 2022-12-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_apilistid_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilistid',
            name='fdPrdtNm',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='apilistid',
            name='fdSbjt',
            field=models.CharField(max_length=500),
        ),
    ]
