# Generated by Django 3.2 on 2023-01-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20221227_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stat_info',
            options={},
        ),
        migrations.AlterField(
            model_name='dollidolstid',
            name='create_date',
            field=models.DateTimeField(default='2023-01-02 00:34:19'),
        ),
        migrations.AlterField(
            model_name='dollidolstid',
            name='lstYmd',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='습득일자'),
        ),
    ]
