# Generated by Django 3.2 on 2022-12-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_dollidolstid_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dollidolstid',
            name='create_date',
            field=models.DateTimeField(default='2022-12-29 09:56:10'),
        ),
    ]
