# Generated by Django 3.2 on 2022-12-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20221227_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dollidolstid',
            name='create_date',
            field=models.DateTimeField(default='2022-12-27 15:42:09'),
        ),
        migrations.AlterField(
            model_name='dollidolstid',
            name='lstYmd',
            field=models.DateField(blank=True, default='2022:12:27 15:42:09', max_length=100, null=True),
        ),
    ]
