# Generated by Django 3.2 on 2022-12-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_stat_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat_info',
            name='count',
        ),
        migrations.AddField(
            model_name='stat_info',
            name='api_cnt',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stat_info',
            name='dollido_cnt',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
