# Generated by Django 3.2 on 2022-12-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20221227_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat_info',
            name='date',
            field=models.DateField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
