# Generated by Django 3.2 on 2022-12-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20221227_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dollidolstid',
            name='create_date',
            field=models.DateTimeField(default='2022-12-27 16:04:34'),
        ),
        migrations.AlterField(
            model_name='dollidolstid',
            name='lstYmd',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
