# Generated by Django 3.2 on 2022-12-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20221226_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dollidolstid',
            name='clrNm',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dollidolstid',
            name='create_date',
            field=models.DateTimeField(default='2022-12-26 16:43:25'),
        ),
        migrations.AlterField(
            model_name='dollidolstid',
            name='lstFilePathImg',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='사진 등록'),
        ),
        migrations.AlterField(
            model_name='dollidolstid',
            name='lstPlace',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dollidolstid',
            name='lstPrdtNm',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='습득물 이름'),
        ),
        migrations.AlterField(
            model_name='dollidolstid',
            name='lstYmd',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dollidolstid',
            name='lstcontent',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='특이사항'),
        ),
    ]
