# Generated by Django 3.2 on 2022-12-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20221227_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dollidolstid',
            name='create_date',
            field=models.DateTimeField(default='2022-12-27 16:16:20'),
        ),
        migrations.AlterField(
            model_name='dollidolstid',
            name='lstYmd',
            field=models.DateTimeField(blank=True, default='2022:12:27 16:16:20', max_length=100, null=True),
        ),
    ]
