# Generated by Django 3.2 on 2023-01-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_dollidolstid_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dollidolstid',
            name='create_date',
            field=models.DateField(default='2023-01-06'),
        ),
        migrations.AlterField(
            model_name='dollidolstid',
            name='lstYmd',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='습득일자'),
        ),
    ]
