# Generated by Django 3.2 on 2022-12-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='이메일 주소', max_length=64, unique=True, verbose_name='email address'),
        ),
    ]
