# Generated by Django 3.2 on 2022-12-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(help_text='현 거주지 주소를 입력해주세요', max_length=30, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='이메일 주소를 입력해주세요', max_length=64, unique=True, verbose_name='이메일 주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='사용자가 활성상태인지 여부 확인계정을 삭제하는 대신 이것을 선택 해제', verbose_name='활성화 상태'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='사용자가 관리사이트에 로그인할 수 있는지 여부 확인', verbose_name='관리자 권한'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(help_text='전화번호를 입력해주세요. 입력 예시 : 01012345678', max_length=11, verbose_name='전화번호'),
        ),
    ]
