# Generated by Django 3.2 on 2022-12-05 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('upper_category', models.CharField(max_length=20)),
                ('middle_category', models.CharField(max_length=20)),
                ('lower_category', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DollidoLstId',
            fields=[
                ('dollido_lst_id', models.AutoField(primary_key=True, serialize=False)),
                ('lstFilePathImg', models.CharField(max_length=300)),
                ('lstSteNm', models.CharField(max_length=100)),
                ('lstLctNm', models.CharField(max_length=200)),
                ('lstPlace', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=15)),
                ('orgNm', models.CharField(max_length=100)),
                ('lstYmd', models.DateField(max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='ApiListId',
            fields=[
                ('api_lst_id', models.AutoField(primary_key=True, serialize=False)),
                ('lstFilePathImg', models.CharField(max_length=300)),
                ('lstSteNm', models.CharField(max_length=100)),
                ('lstLctNm', models.CharField(max_length=200)),
                ('lstPlace', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=15)),
                ('orgNm', models.CharField(max_length=100)),
                ('lstYmd', models.DateField(max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
    ]
