# Generated by Django 3.2 on 2022-12-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200, verbose_name='분실물')),
                ('description', models.TextField(max_length=500, null=True)),
                ('image', models.FileField(blank=True, upload_to='lost_image')),
                ('create_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'lost_item',
            },
        ),
    ]
