# Generated by Django 3.2 on 2022-12-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dollido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lost',
            name='result',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lost',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='특이사항'),
        ),
        migrations.AlterField(
            model_name='lost',
            name='image',
            field=models.FileField(blank=True, upload_to='lost_image', verbose_name='사진 등록'),
        ),
        migrations.AlterField(
            model_name='lost',
            name='item',
            field=models.CharField(max_length=200, verbose_name='분실물 이름'),
        ),
    ]
