# Generated by Django 3.2 on 2022-12-14 01:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dollido', '0006_remove_lost_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
