# Generated by Django 3.2 on 2022-12-14 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dollido', '0007_alter_lost_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DollidoLstId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lstPrdtNm', models.CharField(max_length=200, verbose_name='습득물 이름')),
                ('lstFilePathImg', models.ImageField(blank=True, upload_to='lost_image', verbose_name='사진 등록')),
                ('lstcontent', models.CharField(default='', max_length=500, verbose_name='특이사항')),
                ('lstYmd', models.DateField(max_length=10)),
                ('lstPlace', models.CharField(blank=True, max_length=50)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
