# Generated by Django 3.2 on 2022-12-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dollido', '0008_dollidolstid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dollidolstid',
            name='lstFilePathImg',
            field=models.FileField(blank=True, upload_to='lost_image', verbose_name='사진 등록'),
        ),
    ]
